### ISSUE TITLE
Scaffolding a Piral Instance Fails in Windows

### ISSUE THREAD

**Issue by MattShrider** [smapiot/piral#192] opened 2020-04-15 17:59 UTC
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version
piral@0.11.1
Windows

## Description

Trying to follow the tutorial#1 getting started, says to run `piral new --target my-app`, following this fails to run. It gives me a blank folder with a package.json and nothing else.

## Steps to reproduce
```
$ piral new --target app-shell
> Codes Reference: https://docs.piral.io/code/search
```

## Expected behavior

There should be a new piral instance there with the correct template

## Actual behavior

The folder was empty and `piral debug` fails.

## Possible Origin / Solution

The tutorials may be out of date?

**Comment by MattShrider** [comment] 2020-04-15 18:06
As a follow up https://docs.piral.io/ seems to say that you should instead use `npm init piral-instance`, which DOES work, so this is probably just outdated tutorial pages.

**Comment by FlorianRappl** [comment] 2020-04-15 18:12
> As a follow up https://docs.piral.io/ seems to say that you should instead use npm init piral-instance, which DOES work, so this is probably just outdated tutorial pages.

`npm init piral-instance` uses `piral new` under the hood. The latter is just a pure CLI UX with parameters while the former places a survey upfront to walk through the different options.

So both things should work - and the tutorial is not outdated even though we recommend using `npm init` for a couple of reasons.

I've just tried this in WSL and for me this worked. What version of the `piral-cli` did you install? Is 0.11.1 also the version of the Piral CLI?

```plain
rapplf@DBTNODH:/mnt/c/Users/flori$ piral --version
0.11.1
rapplf@DBTNODH:/mnt/c/Users/flori$ cd /mnt/e/Code/Piral-Playground/
rapplf@DBTNODH:/mnt/e/Code/Piral-Playground$ piral new --target my-app
✨  Successfully scaffolded new Piral instance!      
rapplf@DBTNODH:/mnt/e/Code/Piral-Playground$ cd my-app/
rapplf@DBTNODH:/mnt/e/Code/Piral-Playground/my-app$ ls
node_modules  package.json  src  tsconfig.json
rapplf@DBTNODH:/mnt/e/Code/Piral-Playground/my-app$ npm start

> my-app@1.0.0 start /mnt/e/Code/Piral-Playground/my-app
> piral debug

⚡️  Running at http://localhost:1234.
⚙️  Manage via http://localhost:1234/manage-mock-server.
```

Maybe this is OS related. I'll try in plain Windows later!

Thanks for the report. I'll keep investigating.

**Comment by MattShrider** [comment] 2020-04-15 18:22
Specifically, I was following https://docs.piral.io/tutorials/02-getting-started , so I should have @latest tag of piral-cli, which is piral-cli@0.11.1

**Comment by MattShrider** [comment] 2020-04-15 18:32
Looks like this is windows only, ran in WSL (Ubuntu) and the scaffold worked just fine.

**Comment by FlorianRappl** [comment] 2020-04-15 18:48
> Looks like this is windows only, ran in WSL (Ubuntu) and the scaffold worked just fine.

Thanks for confirming. Will be fixed asap!
:beers:

**Comment by FlorianRappl** [comment] 2020-04-16 09:03
So far I'm unable to reproduce this on my Windows machine. I could find another bug with the verbose logging filename of Parcel's logger on Windows, which will be fixed.

I used:

- NPM v6.1.0
- Node v10.7.0

Executed the scaffolding in PowerShell.

**Comment by axinom-benjamin** [comment] 2020-04-16 09:15
I did some more tries and it's working for me when I use PowerShell directly, but it fails when I run it from the Visual Studio Code integrated PowerShell.
The output on the integrated PowerShell is:
```
PS C:\tmp\piral> piral new --target app-shell
- Preparing source and target ...null
Codes Reference: https://docs.piral.io/code/search
```

It created the `app-shell` folder but it only contains a `package.json`, nothing more.

**Comment by FlorianRappl** [comment] 2020-04-16 09:21
Hm I just tried running from VS Code. Seems to be working so far. I'll try a few variations.

Mind sharing the Node / NPM version? Thanks!

**Comment by axinom-benjamin** [comment] 2020-04-16 09:25
```Powershell
PS C:\tmp> node --version
v12.16.1
PS C:\tmp> npm --version
6.14.4
PS C:\tmp> code --version
1.43.2
0ba0ca52957102ca3527cf479571617f0de6ed50
x64
PS C:\tmp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by FlorianRappl** [comment] 2020-04-16 09:56
I also updated my Node / NPM versions to match this. No success so far - it *always* works.

**Comment by axinom-benjamin** [comment] 2020-04-16 12:38
I did some quick debugging and it seems like the promise in https://github.com/smapiot/piral/blob/23e7fd9a8f9ee8abaee52fd6572601aa40949f73/src/packages/piral-cli/src/apps/new-piral.ts#L85 gets rejected with that error:

```
Error: null
    at ChildProcess.<anonymous> (C:\Users\schwendner\AppData\Roaming\npm\node_modules\piral-cli\lib\common\scripts.js:24:75)
    at ChildProcess.emit (events.js:323:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

though it doesn't really give any hints why the install failed...

**Comment by FlorianRappl** [comment] 2020-04-16 12:51
I guess it may be due to the way the options are provided. But then not sure why it works in one PS and not in the other. I would expect some issue, e.g., with CMD.

Definitely interesting ... Thanks for the investigation so far! :beers:

**Comment by MattShrider** [comment] 2020-04-16 13:57
I'm running in node v10.14.2 and npm 6.4.1 for more info.

**Comment by FlorianRappl** [comment] 2020-04-17 08:06
Still having trouble to reproduce.

For me - no matter the Node and NPM version - it works. It works in PowerShell, works in PS of VS Code (Windows) and also works in plain CMD.

I have a feeling that the problem lies in this part

```js
export function runScript(script: string, cwd = process.cwd(), output: NodeJS.WritableStream = process.stdout) {
  const bin = resolve('./node_modules/.bin');
  const sep = isWindows ? ';' : ':';
  const env = Object.assign({}, process.env);

  env.PATH = `${bin}${sep}${env.PATH}`;
  log('generalDebug_0003', `Running "${script}" in "${cwd}" ("${bin}").`);

  return new Promise<void>((resolve, reject) => {
    const error = new MemoryStream();
    const opt = { end: false };
    const cp = exec(script, {
      cwd,
      env,
    });

    cp.stdout.pipe(output, opt);
    cp.stderr.pipe(error, opt);

    cp.on('error', () => reject(new Error(error.value)));
    cp.on('close', (code, signal) => (code === 0 ? resolve() : reject(new Error(signal))));
  });
}
```

but I don't know which part could be responsible.

I will actually defer this issue to 0.11.3 - and I hope that in the meantime it can be reproduced. Thanks for the infos and efforts so far @MattShrider @axinom-benjamin !

**Comment by FlorianRappl** [comment] 2020-04-30 15:06
Any news on this one?

@MattShrider @axinom-benjamin 

Would love to get a repro on it. So far being not successful, but still hoping :)

**Comment by axinom-benjamin** [comment] 2020-05-06 08:09
no news, unfortunately - working around it by not using the integrated terminal for the CLI.

not sure if it helps anything, but the issue is not happening when using the integrated (bash) terminal of my WSL.

**Comment by FlorianRappl** [comment] 2020-05-24 21:55
With 0.11.5 we at least improved the output.

Maybe we get now more information what could be the root cause for the failure of `npm` under these circumstances.

Any help appreciated! Thanks!

cc @MattShrider  @axinom-benjamin

**Comment by axinom-benjamin** [comment] 2020-05-25 08:53
That did something! It's now telling that `npm.cmd` could not be found.
Though only when executing from the global installation. When installing it locally and running it using npx it works.

```
PS C:\Projects\PiralTest> piral --version
0.11.5
PS C:\Projects\PiralTest> piral new --target app-shell    
- Preparing source and target ...Der Befehl "npm.cmd" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
PS C:\Projects\PiralTest> npx piral-cli new --target app-shell
√  Pilet scaffolded successfully!
```

**Comment by FlorianRappl** [comment] 2020-05-25 09:08
Great - thanks @axinom-benjamin for the insight.

I guess I now have the right pointer. What we do is that we add the local `node_modules/.bin` folder to the PATH, but we assume that the global one is in the path. Apparently, it is not always given.

I'll figure out a way to check that beforehand and potentially add it.

Thanks again for helping here! :beers:

**Comment by FlorianRappl** [comment] 2020-05-26 13:58
There is a potential fix out there.

After installing `npm i -g piral-cli@next` can you try running?

```sh
piral new --target app-shell
```

I'd love to know if the fix is working for this scenario. Otherwise, I'd love to know what's the output if you run:

```sh
echo %PATH:;=&echo.%
```

Thanks for helping us out here @axinom-benjamin

**Comment by axinom-benjamin** [comment] 2020-05-26 15:39
Unfortunately, the issue is still there:

```PowerShell
PS C:\Projects\PiralTest> piral --version
0.11.6-pre.1256
PS C:\Projects\PiralTest> piral new --target app-shell
- Preparing source and target ...Der Befehl "npm.cmd" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
```

Here my path dump:

```PowerShell
PS C:\Projects\PiralTest> $env:path.split(";")
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\wbin
C:\Program Files (x86)\SCE\ORBIS\Tools\Target Manager Server\bin
C:\Program Files (x86)\SN Systems\PS3\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Microsoft\Web Platform Installer\
C:\ProgramData\chocolatey\bin
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\dotnet\
C:\Program Files (x86)\GtkSharp\2.12\bin
C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.121-1\bin
C:\Program Files\PuTTY\
C:\Program Files\Java\jdk1.8.0_144\bin
C:\WINDOWS\System32\OpenSSH\
C:\Program Files (x86)\Microsoft Emulator Manager\1.0\
C:\Program Files\Git\cmd
C:\Go\bin
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files\Microsoft SQL Server\140\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64
C:\Program Files (x86)\Yarn\bin\
C:\nvm
C:\Program Files\nodejs
C:\Program Files\MongoDB\Server\4.0\bin

C:\Program Files\Docker\Docker\resources\bin
C:\ProgramData\DockerDesktop\version-bin
C:\Program Files\nodejs\
C:\Ruby26-x64\bin
C:\Program Files\MySQL\MySQL Shell 8.0\bin\
C:\Users\schwendner\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\schwendner\AppData\Local\Programs\Fiddler
C:\Users\schwendner\AppData\Local\Microsoft\WindowsApps
C:\Users\schwendner\AppData\Local\hyper\app-3.0.2\resources\bin
C:\Users\schwendner\AppData\Roaming\npm
C:\Users\schwendner\AppData\Local\GitHubDesktop\bin
```

**Comment by FlorianRappl** [comment] 2020-05-26 17:08
Thanks a lot - that's helpful!

I'll set it back to "implementation". Let's hope we can tame this beast ;).

**Comment by axinom-benjamin** [comment] 2020-05-27 08:22
fingers crossed :-)

**Comment by FlorianRappl** [comment] 2020-05-27 15:16
Two more things I'll need to ask (sorry @axinom-benjamin ):

1. Can you try `which npm`? What's the result?
2. One of the differences (to my config) I've noted is that the path to nodejs is in there twice. Can you try what happens if you remove one of them? What if you remove the empty entry?

Thanks a lot!

**Comment by axinom-benjamin** [comment] 2020-05-27 15:56
Erm... I managed to fix it - but I'm not sure how... :-(

When running the which/where command it reported be back both locations `C:\Users\schwendner\AppData\Roaming\npm`  as well as `C:\Program Files\nodejs`. Then I went ahead and removed the AppData one from my path. This changed it in a way, that the shell was not able to find the Piral CLI at all anymore. So I decided to run the global installation again - to install it to that installation of npm - which succeeded, but still the command was not found. So I went and added the AppData folder back to the path variable - and then all of the sudden the scaffolding command succeeded...

So I now unfortunately repaired the testing environment for that issue - and I don't know why/how...
I will ask a colleague tomorrow who I think said he was seeing the same issues - maybe we can debug further using his machine.

Here my current setup - (nothing really changed - but it's working now):
```Powershell
PS C:\Projects\PiralTest> where.exe npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
C:\Users\schwendner\AppData\Roaming\npm\npm
C:\Users\schwendner\AppData\Roaming\npm\npm.cmd
PS C:\Projects\PiralTest> $env:path.split(";")        
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\        
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\  
C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\        
C:\Program Files (x86)\Microsoft SDKs\VSTS\CLI\wbin
C:\Program Files (x86)\SCE\ORBIS\Tools\Target Manager Server\bin
C:\Program Files (x86)\SN Systems\PS3\bin
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\Microsoft\Web Platform Installer\
C:\ProgramData\chocolatey\bin
C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
C:\Program Files\dotnet\
C:\Program Files (x86)\GtkSharp\2.12\bin
C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.121-1\bin
C:\Program Files\PuTTY\
C:\Program Files\Java\jdk1.8.0_144\bin
C:\WINDOWS\System32\OpenSSH\
C:\Program Files (x86)\Microsoft Emulator Manager\1.0\
C:\Program Files\Git\cmd
C:\Go\bin
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files\Microsoft SQL Server\140\Tools\Binn\
C:\Program Files\Microsoft SQL Server\140\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64
C:\nvm
C:\Program Files\nodejs
C:\Program Files\MongoDB\Server\4.0\bin

C:\Program Files\Docker\Docker\resources\bin
C:\ProgramData\DockerDesktop\version-bin
C:\Program Files\nodejs\
C:\Program Files (x86)\Yarn\bin\
C:\Ruby26-x64\bin
C:\Program Files\MySQL\MySQL Shell 8.0\bin\
C:\Users\schwendner\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\schwendner\AppData\Local\Programs\Fiddler
C:\Users\schwendner\AppData\Local\Microsoft\WindowsApps
C:\Users\schwendner\AppData\Local\hyper\app-3.0.2\resources\bin
C:\Users\schwendner\AppData\Local\GitHubDesktop\bin
C:\Users\schwendner\AppData\Local\Yarn\bin
C:\Users\schwendner\AppData\Roaming\npm

PS C:\Projects\PiralTest> piral new --target app-shell
√  Piral instance scaffolded successfully!
```

**Comment by FlorianRappl** [comment] 2020-05-27 16:14
I think the `which npm` resulting in two locations may be helpful here.

Right now is it still returning two locations or just one?

**Comment by axinom-benjamin** [comment] 2020-05-28 07:20
yes, the `where npm` is still returning both locations:
```
PS C:\Projects\PiralTest> where.exe npm
C:\Program Files\nodejs\npm
C:\Program Files\nodejs\npm.cmd
C:\Users\schwendner\AppData\Roaming\npm\npm
C:\Users\schwendner\AppData\Roaming\npm\npm.cmd
```

**Comment by FlorianRappl** [comment] 2020-05-29 20:31
There is another trial out there. We would only need someone with a suitable test config ...

**Comment by axinom-benjamin** [comment] 2020-06-02 08:00
I checked with my colleague but he doesn't have that issue on his machine.
But I double-checked it on my machine now and - I absolutely have no idea why but - it's broken again now!
I don't have the CLI installed globally right now because I uninstalled it for one of the tests I did but when I run it using `npx` I'm getting the following output:

```Powershell
PS C:\Projects\PiralTest> npx piral-cli --version
0.11.5
PS C:\Projects\PiralTest> npx piral-cli new --target app-shell     
- Preparing source and target ...Der Befehl "npm.cmd" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
PS C:\Projects\PiralTest> npx piral-cli@next --version        
0.11.6-pre.1324
PS C:\Projects\PiralTest> npx piral-cli@next new --target app-shell
- Preparing source and target ...Der Befehl "where.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
```

does that help?

**Comment by FlorianRappl** [comment] 2020-06-02 11:55
What Windows version is this? Any other special constraints here?

Remark: `where.exe` should be available everywhere. Quite strange. We now use this as a fallback to determine if there are multiple options.

**Comment by axinom-benjamin** [comment] 2020-06-02 12:12
this is Windows 10 Enterprise Version 1909 (Build 18363.778).
No special constraints - that I'm aware of.

`where.exe` is also running well, when executing it from PowerShell directly (in the same one that can not find it when executed by the CLI)

**Comment by FlorianRappl** [comment] 2020-06-02 13:06
All these point in a direction that I have not yet fully understood the problem...

It seems that the process runs in a special sub-shell that for some reason does not share any paths (or env variables at all?) with the parent shell.

I'll keep investigating.

**Comment by FlorianRappl** [comment] 2020-06-02 15:06
Can you give it another spin @axinom-benjamin ? Thanks a lot :beers:! And sorry for bothering you. Trust me, if I could reproduce I would not bother you with these tests 🥇 .

**Comment by axinom-benjamin** [comment] 2020-06-03 11:34
```PS
PS C:\Projects\PiralTest> npx piral-cli@next new --target app-shell
- Preparing source and target ...Der Befehl "where.exe" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
PS C:\Projects\PiralTest> npx piral-cli@next new --version
0.11.6-pre.1372
```
still the same

**Comment by FlorianRappl** [comment] 2020-06-03 11:37
Hm something does not seem right. The latest `next` version does not come with any usage / lookup for `where.exe`.

**Comment by axinom-benjamin** [comment] 2020-06-03 11:58
that's strange indeed...
one more thing to note: I see this issue only when running through `npx` or running `piral` from the global installation.
When running `npm i piral-cli` (only locally installed) first and then executing it from a npm script it will succeed - even with 0.11.5.

and when installing `@next` globally and running the `new` command I get now this:
```PS
PS C:\Projects\PiralTest> piral new --target app-shell
- Preparing source and target ...Der Befehl "npm.cmd" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
PS C:\Projects\PiralTest> piral --version
0.11.6-pre.1372
```

**Comment by FlorianRappl** [comment] 2020-06-03 13:32
Understood. Thanks for the investigation @axinom-benjamin !

One more try please (...). Thanks!

**Comment by axinom-benjamin** [comment] 2020-06-04 08:04
```PS
PS C:\Projects\PiralTest> npx piral-cli@next --version
0.11.6-pre.1380
PS C:\Projects\PiralTest> npx piral-cli@next new --target app-shell
- Preparing source and target ...Der Befehl "npm.cmd" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
Codes Reference: https://docs.piral.io/code/search
```

:worried:

**Comment by FlorianRappl** [comment] 2020-06-04 08:34
Since we cannot reproduce it I would suggest to try `npm cache clean --force` if this has any impact.

We'd now defer that  back to an unknown point in time. Its not a critical issue and it seems to be difficult / very special to reproduce. At least we have not managed to see it on our Windows machines.

Once a solid path for reproduction is known we can look into this again.

**Comment by axinom-benjamin** [comment] 2020-06-04 09:17
still the same after `npm cache clean --force`

But I agree that this issue is not worth hunting further. It sees not really wide-spread and most likely some strange configuration that is happening on my machine. Since there are also very feasible workarounds, so it's not a critical issue at all.

The workarounds (that work on my machine) for the protocol:
- Running from actual Powershell rather than the integrated VS Code terminal works
- Running from global installation works
- Running from local installation through npm scripts work

The only thing that doesn't work is: running it using npx from inside the integrated terminal in VS Code.

Still, thanks for all the time spent trying to find the issue!

**Comment by Robbson** [comment] 2020-10-13 10:34
I get the same issue when using Powershell inside VS Code on my dev machine at work.
In comparison to a standalone Powershell terminal the environment seems partially different.

But it's not an issue for me because I don't use it there.
Just to inform you that I can reproduce it here.

**Comment by FlorianRappl** [comment] 2020-10-13 12:59
Tried in VS Code on my Windows host. I tried `piral new` (global installation) `npx piral new` (using npx task runner) and `npm init piral-instance -y`. All worked.

I am therefore unsure to proceed. I'd love to close (fix) this, but without having a reproducible on my machine it will be difficult. I am quite sure its something about the ENV, but I don't know what.

**Closed** 2020-12-17 18:37 UTC
Labels: bug, cli, cross-platform, help wanted, repro-needed, wontfix, workaround-available

**Comment by peter-at-work** [comment] 2021-12-31 02:11
Our organization has just started looking into _piral_ as an alternative microfrontend framework.

We encountered a possibly-related issue where, in some environments, the `piral build` also had a problem finding the _npm_ command during the packaging step of the _piral_ instance.

Tracked it down to a Windows environment where _nodejs_ is not installed in the standard location because it was installed as non-administrator.  In this case, `npm.cmd` was installed in some path like `C:\Users\USER\apps\nodejs` and that path is added to the Windows `PATH` environment variable.

As discovered in https://github.com/smapiot/piral/issues/192#issuecomment-615106475, the `scripts.ts` code is incorrectly using the `env` object `Path` property because of case-sensitivity as described in https://github.com/nodejs/node/issues/20605

Fixed it in `scripts.ts` with the following (changing all `env.PATH` to `env.Path`):
```
export function runScript(script: string, cwd = process.cwd(), output: NodeJS.WritableStream = process.stdout) {
  const bin = resolve('./node_modules/.bin');
  const sep = isWindows ? ';' : ':';
  const env = Object.assign({}, process.env);

  env.Path = `${bin}${sep}${env.Path}`;
  log('generalDebug_0003', `Running "${script}" in "${cwd}" ("${bin}").`);

  if (isWindows) {
    // on windows we sometimes may see a strange behavior,
    // see https://github.com/smapiot/piral/issues/192
    const newPaths = [
      resolveWinPath('AppData', 'npm'),
      resolveWinPath('ProgramFiles', 'nodejs'),
      resolveWinPath('ProgramFiles(x86)', 'nodejs'),
      ...env.Path.split(';'),
    ];
    env.Path = newPaths.filter(Boolean).join(sep);
  }
  ...
```

I'd like to initiate a PR, but I get failures on the latest _develop_ branch on building `piral-cli-webpack5`.

**Comment by FlorianRappl** [comment] 2021-12-31 13:33
> I'd like to initiate a PR, but I get failures on the latest develop branch on building piral-cli-webpack5.

Yeah just do the PR (much appreciated!) - we can handle the build failure separately!

**Comment by FlorianRappl** [comment] 2021-12-31 13:39
(I also need to point out that we need to be careful here. `process.env.PATH` is **not** `process.env.Path`. On Linux you'd get `undefined` in the latter case. I think we need to distinguish the OS here. And by the way, with Node 16 both ways also seem to work fine on Windows, so I'm not sure if that is indeed the issue / fix.)

**Comment by peter-at-work** [comment] 2022-01-07 01:06
@FlorianRappl Thanks for pointing that out, and I had to rework my fix.  Spawning a child process still looks for the `PATH` property on the `env` options, so I made the change only for a Windows environment.  See changes in PR https://github.com/smapiot/piral/pull/444
