### ISSUE TITLE
piral-breadcrumbs not resolving correct ptr version

### ISSUE THREAD

**Issue by rolando-valdivia-incontact** [smapiot/piral#385] opened 2021-06-17 21:23 UTC
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

OS: OSX
Browser: Chrome
Piral version: 0.13.2

## Description

It looks like "path-to-regexp" was updated and it is exporting multiple functions causing getMatcher function to fail and making impossible to register breadcrumbs.

```
Uncaught TypeError: ptr is not a function
    at getMatcher (create.ts:24)
    at Object.registerBreadcrumb (create.ts:79)
```

## Steps to Reproduce

1. Run any piral sample or create a new project
    - Execute the app and make sure it works as expected.
2. Add createBreadcrumbsApi()
3. register a new breadcrumb.
```js
app.registerBreadcrumb('bc-id', {
  title: 'Example',
  path: '/example',
});
```
4. Execute the app
    - The page is blank
    - The console displays "Uncaught TypeError: ptr is not a function"

## Expected behavior

app.registerBreadcrumb can register breadcrumbs.

## Actual behavior

when a breadcrumb is registered, the following error message is displayed in browser console:

```
Uncaught TypeError: ptr is not a function
    at getMatcher (create.ts:24)
    at Object.registerBreadcrumb (create.ts:79)
```

## Possible Origin / Solution

- Update line 11 and 14 of create.js from:

Line: 11   return ptr(settings.matcher); -> return ptr.compile(settings.matcher);
Line: 14   return ptr(settings.path); -> return ptr.compile(settings.path);

**Comment by FlorianRappl** [comment] 2021-06-17 22:17
What bundler and NPM client (NPM v?, Yarn v?, ...) did you use?

I ask because `piral-breadcrumbs` *depends* on `path-to-regexp@^1.8` (see, e.g., https://github.com/pillarjs/path-to-regexp/tree/v1.7.0): https://github.com/smapiot/piral/blob/develop/src/plugins/piral-breadcrumbs/package.json#L47

Therefore, the problem is not that ptr changed, but rather that this dependency is either not correctly resolved or installed. We use `piral-breadcrumbs` in production (e.g., on the Piral Cloud Feed Service portal) and never experienced an issue.

**Comment by rolando-valdivia-incontact** [comment] 2021-07-26 17:34
Hi @FlorianRappl, sorry for the late response, I just had chance to review this in more detail.

In summary the problem occur when bundling a shell or pilet using parcel, same result with npm or yarn.

I'm using parcel to build pilets that depends on converters.

This is the minimum code required to reproduce the issue, when you build using webpack it works properly, but when you build using parcel, it throws: 

> Uncaught TypeError: ptr is not a function
>     at getMatcher (create.ts:24)
>     at getBreadcrumbs (create.ts:35)

```node
import 'piral/polyfills';
import { renderInstance } from 'piral';
import { layout, errors } from './layout';
import { createBreadcrumbsApi } from 'piral-breadcrumbs';

// change to your feed URL here (either using feed.piral.cloud or your own service)
const feedUrl = 'https://feed.piral.cloud/api/v1/pilet/empty';

renderInstance({
  layout,
  errors,
  plugins: [createBreadcrumbsApi(
    {
      breadcrumbs: [
        {
          path: '/example',
          title: 'Example',
        },
        {
          path: '/example/foo',
          title: 'Foo',
          parent: '/example',
        },
      ]
    }
  )],
  requestPilets() {
    return fetch(feedUrl)
      .then(res => res.json())
      .then(res => res.items);
  },
});
```

You can also build the shell using webpack and it will work as expected, but a pilet built with parcel using this shell will fail with the same error.

Any advice/workaround on how to make this work using parcel will be appreciated.

PS: Thanks a lot for this amazing project!

**Comment by FlorianRappl** [comment] 2021-07-26 18:25
> This is the minimum code required to reproduce the issue, when you build using webpack it works properly, but when you build using parcel, it throws:

It is not. We also use Parcel for the Piral Feed Service Portal and it works without a problem. While its true that Parcel is worse than Webpack in resolving the "correct" module the origin of the problem is 100% the packages that you installed.

Find out why you have multiple versions of `path-to-regexp` installed and if the node_modules structure looks fine. My feeling is that your tree got corrupted and you should `rm -rf node_modules yarn.lock package-lock.json` before re-installing the packages.

Again, since we also use Parcel and here it works fine I cannot give you a workaround; I can only tell what you should look at to debug where the bundler goes wrong. In the end, however, there is nothing we can do here. The dependency is specified correctly on our side. If you find out what goes wrong here and have a fix I'd appreciate it!

**Comment by rolando-valdivia-incontact** [comment] 2021-07-26 18:42
This is the source code of a brand new shell (0.13.2) , no additional modules, you don't even need a pilet to reproduce.

- piral new --target myShell
- cd myShell/
- npm i piral-breadcrumbs
- Add these to index.tsx

```node
import { createBreadcrumbsApi } from 'piral-breadcrumbs';
```

```node
plugins: [createBreadcrumbsApi(
    {
      breadcrumbs: [
        {
          path: '/example',
          title: 'Example',
        },
        {
          path: '/example/foo',
          title: 'Foo',
          parent: '/example',
        },
      ]
    }
  )],

- piral debug --bundler parcel
- Go to http://localhost:1234
```

Full package.json

```json
{
  "name": "myShell",
  "version": "1.0.0",
  "description": "",
  "keywords": [
    "piral"
  ],
  "dependencies": {
    "piral": "^0.13.2",
    "piral-breadcrumbs": "^0.13.2"
  },
  "scripts": {
    "start": "piral debug",
    "build": "piral build"
  },
  "app": "./src/index.html",
  "pilets": {
    "files": [],
    "externals": [],
    "scripts": {},
    "validators": {},
    "devDependencies": {},
    "preScaffold": "",
    "postScaffold": "",
    "preUpgrade": "",
    "postUpgrade": "",
    "packageOverrides": {}
  },
  "devDependencies": {
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@types/react-router": "latest",
    "@types/react-router-dom": "latest",
    "piral-cli": "0.13.2",
    "piral-cli-parcel": "^0.13.2",
    "typescript": "latest"
  }
}

```

**Comment by FlorianRappl** [comment] 2021-07-26 18:45
> This is the source code of a brand new shell (0.13.2) , no additional modules, you don't even need a pilet to reproduce.

Have you read my comment? We use Parcel and have the same setup. Also the critical information you still leave out; how the modules are laid out. As described the problem is not coming from `piral-breadcrumbs` as it states the dependency correctly.

**Comment by FlorianRappl** [comment] 2021-07-26 19:18
Alright I had a second look at the issue. We actually have a custom babel rc for our cloud portal as this is one of the Parcel "standard" side-effects, i.e., when an esm imports a module its exports are "auto-converted" to ESM-compatible exports. Therefore, the `*` export is becoming `default`. Unfortunately, it does convert the imports...

With `require` it works though. I'll change it in the 0.13.3 release and then it should work under these conditions, too.

Thanks for the reproducible!

**Closed** 2021-07-28 11:50 UTC
Labels: bug, in-implementation, parcel
