### ISSUE TITLE
piral-ng not working. Getting "Can't resolve all parameters for NgExtension:"

### ISSUE THREAD

**Issue by satishjs2297** [smapiot/piral#376] opened 2021-04-18 04:49 UTC
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Package Version: 

    "@angular/common": "^11.2.10",
    "@angular/compiler": "^11.2.10",
    "@angular/core": "^11.2.10",
    "@angular/platform-browser": "^11.2.10",
    "@angular/platform-browser-dynamic": "^11.2.10",
    "piral": "^0.13.1",
    "piral-ng": "^0.13.1",
    "rxjs": "^6.6.7",
    "zone.js": "^0.11.4"

OS: MAC & Windows
Browser: Chrome, Safari

## Description

Unhandled Promise rejection: Can't resolve all parameters for NgExtension: (?, [object Object]). ; Zone: <root> ; Task: Promise.then ; Value: Error: Can't resolve all parameters for NgExtension: (?, [object Object]).

## Steps to Reproduce

Followed the steps documented here
https://www.npmjs.com/package/piral-ng

Here is my github repo: https://github.com/satishjs2297/piral-demo-stuff

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment] 2021-04-18 12:42
Hardly a bug. I think you missed the dependencies part. Please have a look:

https://github.com/smapiot/piral/blob/develop/src/converters/piral-ng/package.json#L55

Angular 11 is not officially supported. If you want to have it supported any kind of contribution is welcome.

I close this one (as its not a bug); feel free to open another issue with Angular 11 support to track some work being done there. Currently, we have no plans of investing more in Angular. Thanks!

**Closed by FlorianRappl** 2021-04-18 12:42 UTC
Labels: bug

**Comment by satishjs2297** [comment] 2021-04-18 14:56
After applying Angular 8.0.0 version, getting below exception ..

Unhandled Promise rejection: Can't resolve all parameters for ApplicationModule: (?). ; Zone: <root> ; Task: Promise.then ; Value: Error: Can't resolve all parameters for ApplicationModule: (?).



Thanks much FlorianRappl for your quick response. I have created pilet-angular-demo-1 project with your recommended version. but got above exception. 
https://github.com/satishjs2297/piral-demo-stuff/tree/master/pilet-angular-demo-1

Do you have any sample angular pilet let and app shell project which I can refer the dependency configuration. I am sure, it is because of dependency compatibility issue. Can you please help us with the right configuration

**Comment by FlorianRappl** [comment] 2021-04-18 18:36
https://github.com/smapiot/sample-cross-fx-pilets/tree/master/ng

**Comment by sbley** [comment] 2021-07-15 15:08
HI @satishjs2297, I see the same error in my sample project using Angular 8.2.14:
```
zone.js:703 Unhandled Promise rejection: Can't resolve all parameters for ApplicationModule: (?). ; Zone: <root> ; Task: Promise.then ; Value: Error: Can't resolve all parameters for ApplicationModule: (?).
```
Have you found a solution for this in the meantime?

**Comment by FlorianRappl** [comment] 2021-07-26 22:18
Following the documentation you'd need to add some more dependencies that are required for Angular (namely reflect and zone). See my comment here: https://github.com/satishjs2297/piral-demo-stuff/issues/1

(The documentation of `piral-ng` also mentions this; it's a bit unfortunate as Angular requires quite a lot of things that are otherwise quite hidden / not so easy to spot)

**Comment by sbley** [comment] 2021-07-27 07:48
I have these imports in my pilet's `index.ts`:

```ts
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
```

Your comment suggests slightly different imports of core-js and zone.js, and you recommend to put them in the app shell's index file (I would expect them only in the pilet). Is this for a reason?

**Comment by FlorianRappl** [comment] 2021-07-27 08:34
The variant you use `core-js/es7/reflect` is only valid for an older version of core-js.

**Comment by sbley** [comment] 2021-07-27 09:06
> The variant you use core-js/es7/reflect is only valid for an older version of core-js.

Apparently, it is for core-js 2.x.x which is also used in @satishjs2297's repo.
The import is also as documented in the piral-ng converter's [README](https://github.com/smapiot/piral/tree/14f07c83fa3835b60cbba54a4b69680bc7bf946f/src/converters/piral-ng#usage).

The imports you mentioned are probably valid for core-js 3.x.x.

With the imports I mentioned in the [comment above](https://github.com/smapiot/piral/issues/376#issuecomment-887291620) at the top of the app shell's `index.tsx` I get the error message "Can't resolve all parameters..."

**Comment by FlorianRappl** [comment] 2021-07-27 09:46
> Apparently, it is for core-js 2.x.x which is also used in @satishjs2297's repo

Yes - as written this is outdated. He should update. There is also quite an important warning when installing the outdated version...

Note that the outdated version is not the problem. He did not use the imports at all. Nevertheless, when correctly using it I recommend using the latest version.

(For completeness: The remark with the updated version was the answer to your question "why does it look different".)

**Comment by sbley** [comment] 2021-07-27 12:02
I finally managed to display an Angular component in a pilet 🎉

What I did is update `core-js` to version 3 and add these imports to the app shell's `index.tsx`:
```
import 'core-js/es/reflect';
import 'core-js/stable/reflect';
import 'core-js/features/reflect';
import 'zone.js/dist/zone';
```

After some trial and error I found that I have to downgrade `core-js` from the latest version to `~3.5.0`. Apparently, there have been changes in `3.6.x` that do not work with Angular 8.

(I also removed `core-js` from the pilet's dependencies because it is provided by Angular since version 8.)

**Comment by FlorianRappl** [comment] 2021-07-27 12:18
It's a good remark with the specific version of core-js.

I'll add `core-js` as a peer dependency to `piral-ng` to indicate that this is required.
